# config/meta.yml
meta_title: "Bartuur"
meta_description: "Exchanger your goods, with others. The oportunities are limitless!"
meta_image: "logo_nicole.jpg" # Une image dans votre dossier app/assets/images/

